version: '3.8'

services:
  web:
    build: darts-calculator
    ports:
      - "9800:80"
    volumes:
      - ./darts-calculator:/var/www/html
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: darts_user
      DB_PASS: darts_password
      DB_NAME: darts_live

  db:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: darts_root_password
      MYSQL_DATABASE: darts_live
      MYSQL_USER: darts_user
      MYSQL_PASSWORD: darts_password
    volumes:
      - ./db_data:/var/lib/mysql

#  phpmyadmin:
#    image: phpmyadmin/phpmyadmin
#    ports:
#      - "9801:80"
#    environment:
#      PMA_HOST: db
#      PMA_USER: darts_user
#      PMA_PASSWORD: darts_password
#    depends_on:
#      - db

